apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-social
  labels:
    app: social
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: social
      name: media-social
  template:
    metadata:
      labels:
        app: social
        name: media-social
    spec:
      containers:
      - name: media
        image: registry.git.famtechvn.net/nodejs/media:latest
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: media-social
      imagePullSecrets:
      - name: media-social-cred